version: "3.8"
volumes:
  n8n:
x-shared: &shared
  restart: always
  image: n8nio/n8n:${SOFTWARE_VERSION_TAG}
  environment:
    EXECUTIONS_MODE: queue
    WEBHOOK_TUNNEL_URL: https://${DOMAIN}
    WEBHOOK_URL: https://${DOMAIN}
    N8N_BASIC_AUTH_ACTIVE: "true"
    N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
    N8N_BASIC_AUTH_PASSWORD: ${SOFTWARE_PASSWORD}
    N8N_HOST: ${DOMAIN}
    N8N_EMAIL_MODE: ${N8N_EMAIL_MODE}
    N8N_SMTP_SENDER: ${N8N_SMTP_SENDER}
    N8N_SMTP_HOST: ${N8N_SMTP_HOST}
    N8N_SMTP_PORT: ${N8N_SMTP_PORT}
    N8N_SMTP_USER: ${N8N_SMTP_USER}
    N8N_SMTP_PASS: ${N8N_SMTP_PASS}
    EXECUTIONS_DATA_PRUNE: ${EXECUTIONS_DATA_PRUNE}
    EXECUTIONS_DATA_MAX_AGE: ${EXECUTIONS_DATA_MAX_AGE}
    EXECUTIONS_DATA_PRUNE_MAX_COUNT: ${EXECUTIONS_DATA_PRUNE_MAX_COUNT}
    DB_TYPE: ${DB_TYPE}
    DB_POSTGRESDB_HOST: ${DB_POSTGRESDB_HOST}
    DB_POSTGRESDB_PORT: ${DB_POSTGRESDB_PORT}
    DB_POSTGRESDB_DATABASE: ${DB_POSTGRESDB_DATABASE}
    DB_POSTGRESDB_USER: ${DB_POSTGRESDB_USER}
    DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
    DB_POSTGRESDB_SCHEMA: ${DB_POSTGRESDB_SCHEMA}
    ADMIN_EMAIL: ${ADMIN_EMAIL}
    N8N_LOG_LEVEL: ${N8N_LOG_LEVEL}
    N8N_METRICS: ${N8N_METRICS}
    N8N_METRICS_INCLUDE_API_ENDPOINTS: ${N8N_METRICS_INCLUDE_API_ENDPOINTS}
    N8N_METRICS_INCLUDE_API_PATH_LABEL: ${N8N_METRICS_INCLUDE_API_PATH_LABEL}
    N8N_METRICS_INCLUDE_API_METHOD_LABEL: ${N8N_METRICS_INCLUDE_API_METHOD_LABEL}
    N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL: ${N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL}
    GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
    QUEUE_BULL_PREFIX: ${QUEUE_BULL_PREFIX}
    QUEUE_BULL_REDIS_DB: ${QUEUE_BULL_REDIS_DB}
    QUEUE_BULL_REDIS_HOST: ${QUEUE_BULL_REDIS_HOST}
    QUEUE_BULL_REDIS_PORT: ${QUEUE_BULL_REDIS_PORT}
    QUEUE_BULL_REDIS_PASSWORD: ${QUEUE_BULL_REDIS_PASSWORD}
    QUEUE_BULL_REDIS_TIMEOUT_THRESHOLD: ${QUEUE_BULL_REDIS_TIMEOUT_THRESHOLD}
    QUEUE_RECOVERY_INTERVAL: ${QUEUE_RECOVERY_INTERVAL}
    QUEUE_WORKER_TIMEOUT: ${QUEUE_WORKER_TIMEOUT}
    QUEUE_HEALTH_CHECK_ACTIVE: ${QUEUE_HEALTH_CHECK_ACTIVE}
  volumes:
    - ./n8n:/home/node/.n8n
services:
  n8n:
    <<: *shared
    dns:
      - 8.8.8.8    
    ports:
      - 172.17.0.1:5678:5678
  n8n-worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n
